/**
 * Familias de set: o MESMO set que o catalogo guarda com mais de um set_id.
 *
 * ★ Por que existe (#313, 13/09/2026). Agrupando a Colecao por set, o Du viu
 * "Chaos Rising" duas vezes na propria colecao. Uma auditoria dos 863 sets do
 * catalogo (so leitura, conferida numero a numero e pela ARTE das cartas, com
 * contraprova) mostrou dois casos diferentes, e os dois entram aqui:
 *
 *  1. IDIOMA: o mesmo set em portugues e em ingles com set_id separado. O
 *     rodape impresso prova: cri diz "CRI PT 010/086", me4 diz "CRI EN". Esses
 *     NUNCA podem ser fundidos no banco -- seria jogar a carta PT de 52
 *     usuarios dentro do set ingles.
 *  2. CADASTRO DUPLICADO: o mesmo set, mesmo idioma, importado duas vezes com
 *     convencoes de id diferentes (ex: base1 x bs, xy9 x bkp).
 *
 * Nos dois casos a Colecao mostra UM grupo, que e o que o colecionador procura.
 * O banco nao muda: fundir cadastro duplicado exige migrar vinculo carta a
 * carta e e decisao separada.
 *
 * Ficaram de fora de proposito os set_ids que misturam dois produtos no mesmo
 * id (g1 = Generations + Gym Heroes; trainer kits combinados xyt*, bwt1, hst1):
 * agrupar por id juntaria sets diferentes.
 *
 * Formato: [chave da familia, nome exibido, set_ids]. A chave e o id oficial.
 */
type Familia = { chave: string; nome: string; sets: string[] }

const FAMILIAS: Array<[string, string, string[]]> = [
  ['sv3pt5', '151', ['mew', 'sv3pt5']],
  ['wcs23', '2023 World Championships Yokohama Deck: Pikachu', ['liga-wcs23', 'wcs23']],
  ['xy7', 'Ancient Origins', ['aor', 'liga-aor', 'xy7']],
  ['sv4k', 'Ancient Roar', ['liga-sv4k', 'sv4k']],
  ['ecard2', 'Aquapolis', ['aq', 'ecard2']],
  ['pl4', 'Arceus', ['ar', 'pl4']],
  ['me2pt5', 'Ascended Heroes', ['asc', 'me2pt5']],
  ['bstg', 'Astros Cintilantes - Galeria de Treinadores', ['bstg', 'liga-bstg']],
  ['base1', 'Base', ['base1', 'bs']],
  ['b2', 'Base Set 2', ['b2', 'base4']],
  ['b24dd', 'Battle Academy 2024 - Darkrai Deck', ['b24dd', 'liga-b24dd']],
  ['bae22', 'Battle Academy Box Set 2022 - Eevee Deck', ['bae22', 'liga-bae22']],
  ['s9a', 'Battle Region', ['liga-s9a', 's9a']],
  ['swsh5', 'Battle Styles', ['bst', 'swsh5']],
  ['bw1', 'Black & White', ['blw', 'bw1']],
  ['clk', 'Blastoise & Suicune ex Deck (JP)', ['clk', 'liga-clk']],
  ['bw7', 'Boundaries Crossed', ['bcr', 'bw7']],
  ['xy9', 'BREAKpoint', ['bkp', 'xy9']],
  ['xy8', 'BREAKthrough', ['bkt', 'xy8']],
  ['sm3', 'Burning Shadows', ['bus', 'sm3']],
  ['bwp', 'BW Black Star Promos', ['bwp', 'bwpr']],
  ['col1', 'Call of Legends', ['cl', 'col1']],
  ['cel25', 'Celebrations', ['cel', 'cel25']],
  ['cel25c', 'Celebrations: Classic Collection', ['ccc', 'cel25c', 'liga-ccc']],
  ['sm7', 'Celestial Storm', ['ces', 'sm7']],
  ['swsh35', 'Champion\'s Path', ['cpa', 'swsh35']],
  ['me4', 'Chaos Rising', ['cri', 'me4']],
  ['cll', 'Charizard & Ho-Oh ex Deck (JP)', ['cll', 'liga-cll']],
  ['swsh6', 'Chilling Reign', ['cre', 'swsh6']],
  ['eb11', 'Basic Energy 2011', ['eb11', 'liga-eb11']],
  ['eb13', 'Basic Energy 2013', ['eb13', 'liga-eb13']],
  ['sm12', 'Cosmic Eclipse', ['cec', 'sm12']],
  ['sm4', 'Crimson Invasion', ['cin', 'sm4']],
  ['swsh12pt5', 'Crown Zenith', ['crz', 'swsh12pt5']],
  ['swsh12pt5gg', 'Crown Zenith Galarian Gallery', ['czgg', 'swsh12pt5gg']],
  ['ex14', 'Crystal Guardians', ['cg', 'ex14']],
  ['sv5m', 'Cyber Judge', ['liga-sv5m', 'sv5m']],
  ['bw5', 'Dark Explorers', ['bw5', 'dex']],
  ['swsh3', 'Darkness Ablaze', ['daa', 'swsh3']],
  ['sv10', 'Destined Rivals', ['dri', 'sv10']],
  ['spd', 'Deoxys VSTAR & VMAX High-Class Deck', ['liga-spd', 'spd']],
  ['dp1', 'Diamond & Pearl', ['dp', 'dp1']],
  ['tk3b', 'Diamond & Pearl Trainer Kit - Lucario', ['liga-tk3b', 'tk3b']],
  ['tk3a', 'Diamond & Pearl Trainer Kit - Manaphy', ['liga-tk3a', 'tk3a']],
  ['dc1', 'Double Crisis', ['dc1', 'dcr', 'liga-dcr']],
  ['ex15', 'Dragon Frontiers', ['df', 'ex15']],
  ['sm75', 'Dragon Majesty', ['drm', 'sm75']],
  ['dv1', 'Dragon Vault', ['drv', 'dv1']],
  ['bw6', 'Dragons Exalted', ['bw6', 'drx']],
  ['bw2', 'Emerging Powers', ['bw2', 'epo']],
  ['sm1p', 'Enhanced Expansion Pack Sun & Moon', ['liga-sm1p', 'sm1p']],
  ['sspjp', 'Espada e Escudo Promos (JP)', ['liga-sspjp', 'sspjp']],
  ['xy12', 'Evolutions', ['evo', 'xy12']],
  ['swsh7', 'Evolving Skies', ['evs', 'swsh7']],
  ['sval', 'ex Starter Set Fuecoco & Ampharos ex', ['liga-sval', 'sval']],
  ['svom', 'ex Starter Set Marnie\'s Morpeko & Grimmsnarl ex', ['liga-svom', 'svom']],
  ['svaw', 'ex Starter Set Quaxly & Mimikyu ex', ['liga-svaw', 'svaw']],
  ['tk2m', 'EX Trainer Kit - Minun', ['tk2b', 'tk2m']],
  ['tk2a', 'EX Trainer Kit 2 Plusle', ['tk2a', 'tk2p']],
  ['ecard1', 'Expedition Base Set', ['ecard1', 'ex']],
  ['xy10', 'Fates Collide', ['fco', 'xy10']],
  ['xy2', 'Flashfire', ['flf', 'xy2']],
  ['sm6', 'Forbidden Light', ['fli', 'sm6']],
  ['base3', 'Fossil', ['base3', 'fo']],
  ['xy3', 'Furious Fists', ['ffi', 'xy3']],
  ['swsh8', 'Fusion Strike', ['fst', 'swsh8']],
  ['cbb1c', 'Gem Pack Volume 1', ['cbb1c', 'liga-cbb1c']],
  ['svm', 'Generations Start Decks', ['liga-svm', 'svm']],
  ['dp4', 'Great Encounters', ['dp4', 'ge']],
  ['sm2', 'Guardians Rising', ['gri', 'sm2']],
  ['sm8b', 'GX Ultra Shiny', ['liga-sm8b', 'sm8b']],
  ['g2', 'Gym Challenge', ['g2', 'gym2']],
  ['hgss1', 'HeartGold & SoulSilver', ['hgss1', 'hs']],
  ['sm115', 'Hidden Fates', ['hif', 'sm115']],
  ['ex13', 'Holon Phantoms', ['ehp', 'ex13']],
  ['sv9a', 'Hot Wind Arena', ['liga-sv9a', 'sv9a']],
  ['hgss4', 'HS—Triumphant', ['hgss4', 'tm']],
  ['hgss3', 'HS—Undaunted', ['hgss3', 'ud']],
  ['hgss2', 'HS—Unleashed', ['hgss2', 'ul']],
  ['xyb', 'Hyper Metal Chain Deck', ['liga-xyb', 'xyb']],
  ['ptgd', 'Infernape vs Gallade - Gallade Half Deck', ['liga-ptgd', 'ptgd']],
  ['ptid', 'Infernape vs Gallade - Infernape Half Deck', ['liga-ptid', 'ptid']],
  ['sv9', 'Journey Together', ['jtg', 'liga-jtg', 'sv9']],
  ['base2', 'Jungle', ['base2', 'ju']],
  ['xy0', 'Kalos Starter Set', ['kss', 'xy0']],
  ['base6', 'Legendary Collection', ['base6', 'lc']],
  ['bw11', 'Legendary Treasures', ['bw11', 'ltr']],
  ['dp6', 'Legends Awakened', ['dp6', 'la']],
  ['swsh11', 'Lost Origin', ['lor', 'swsh11']],
  ['swsh11tg', 'Lost Origin Trainer Gallery', ['lortg', 'swsh11tg']],
  ['sm8', 'Lost Thunder', ['lot', 'sm8']],
  ['xya', 'M Charizard-EX Mega Battle Deck', ['liga-xya', 'xya']],
  ['cp1', 'Magma Gang VS Aqua Gang: Double Crisis', ['cp1', 'liga-cp1']],
  ['dp5', 'Majestic Dawn', ['dp5', 'md']],
  ['mc18e', 'McDonald\'s Collection 2018 (English)', ['mc18e', 'mcd18']],
  ['mc21', 'McDonald\'s Collection 2021', ['mc21', 'mcd21']],
  ['mcd1', 'McDonald’s Collection 2011', ['mcd1', 'mcd11']],
  ['mcd2', 'McDonald’s Collection 2012', ['mcd12', 'mcd2']],
  ['me1', 'Mega Evolution', ['me1', 'meg']],
  ['mcrp', 'Movie Commemoration Random Pack', ['liga-mcrp', 'mcrp']],
  ['mfbb', 'My First Battle - Bulbasaur Deck', ['liga-mfbb', 'mfbb']],
  ['mfbc', 'My First Battle - Charmander Deck', ['liga-mfbc', 'mfbc']],
  ['mfbp', 'My First Battle - Pikachu Deck', ['liga-mfbp', 'mfbp']],
  ['mfbs', 'My First Battle - Squirtle Deck', ['liga-mfbs', 'mfbs']],
  ['dp2', 'Mysterious Treasures', ['dp2', 'mt']],
  ['n4', 'Neo Destiny', ['n4', 'neo4']],
  ['n2', 'Neo Discovery', ['n2', 'neo2']],
  ['n1', 'Neo Genesis', ['n1', 'neo1']],
  ['n3', 'Neo Revelation', ['n3', 'neo3']],
  ['bw4', 'Next Destinies', ['bw4', 'nxd']],
  ['bw3', 'Noble Victories', ['bw3', 'nvi']],
  ['sv3', 'Obsidian Flames', ['obf', 'sv3']],
  ['sv2', 'Paldea Evolved', ['pal', 'sv2']],
  ['sv4pt5', 'Paldean Fates', ['paf', 'sv4pt5']],
  ['sv4', 'Paradox Rift', ['par', 'sv4']],
  ['me3', 'Perfect Order', ['me3', 'por']],
  ['me2', 'Phantasmal Flames', ['me2', 'pfl']],
  ['xy4', 'Phantom Forces', ['phf', 'xy4']],
  ['bw10', 'Plasma Blast', ['bw10', 'plb']],
  ['bw9', 'Plasma Freeze', ['bw9', 'plf']],
  ['bw8', 'Plasma Storm', ['bw8', 'pls']],
  ['ppps5', 'Play! Pokémon Prize Pack Series Five', ['liga-ppps5', 'ppps5']],
  ['ppps4', 'Play! Pokémon Prize Pack Series Four', ['liga-ppps4', 'ppps4']],
  ['ppps6', 'Play! Pokémon Prize Pack Series Six', ['liga-ppps6', 'ppps6']],
  ['ppps3', 'Play! Pokémon Prize Pack Series Three', ['liga-ppps3', 'ppps3']],
  ['sv2am', 'Pokémon Card 151: Master Ball', ['liga-sv2am', 'sv2am']],
  ['ru1', 'Pokémon Rumble', ['ru', 'ru1']],
  ['cs4ac', 'Polychromatic Gathering - Friend', ['cs4ac', 'liga-cs4ac']],
  ['p5', 'POP Series 5', ['p5', 'pop5']],
  ['p7', 'POP Series 7', ['p7', 'pop7']],
  ['xy5', 'Primal Clash', ['prc', 'xy5']],
  ['sv8pt5', 'Prismatic Evolutions', ['pre', 'sv8pt5']],
  ['swsh2', 'Rebel Clash', ['rcl', 'swsh2']],
  ['pl2', 'Rising Rivals', ['pl2', 'rr']],
  ['xy6', 'Roaring Skies', ['ros', 'xy6']],
  ['ex1', 'Ruby & Sapphire', ['ex1', 'rs']],
  ['ex2', 'Sandstorm', ['ex2', 'ss']],
  ['dp3', 'Secret Wonders', ['dp3', 'sw']],
  ['swsh45', 'Shining Fates', ['shf', 'swsh45']],
  ['swsh45sv', 'Shining Fates Shiny Vault', ['sfs', 'swsh45sv']],
  ['sm35', 'Shining Legends', ['liga-slg', 'slg', 'sm35']],
  ['sv6pt5', 'Shrouded Fable', ['sfa', 'sv6pt5']],
  ['swsh12', 'Silver Tempest', ['sit', 'swsh12']],
  ['swsh12tg', 'Silver Tempest Trainer Gallery', ['liga-sittg', 'sittg', 'swsh12tg']],
  ['xy11', 'Steam Siege', ['sts', 'xy11']],
  ['sv7', 'Stellar Crown', ['scr', 'sv7']],
  ['svk', 'Stellar Miracle Deck Build Box', ['liga-svk', 'svk']],
  ['s10a', 'Strength Expansion Pack: Dark Phantasma', ['liga-s10a', 's10a']],
  ['sm1', 'Sun & Moon', ['sm1', 'sum']],
  ['tk10b', 'Sun & Moon Trainer Kit - Alolan Raichu', ['liga-tk10b', 'tk10b']],
  ['sv8jp', 'Super Electric Breaker (JP)', ['liga-sv8', 'sv8jp']],
  ['pl3', 'Supreme Victors', ['pl3', 'sv']],
  ['swsh1', 'Sword & Shield', ['ssh', 'swsh1']],
  ['ex4', 'Team Magma vs Team Aqua', ['ex4', 'ma']],
  ['base5', 'Team Rocket', ['base5', 'tr']],
  ['ex7', 'Team Rocket Returns', ['ex7', 'trr']],
  ['sm9', 'Team Up', ['sm9', 'teu']],
  ['sv5', 'Temporal Forces', ['sv5', 'tef']],
  ['sm7a', 'Thunderclap Spark', ['liga-sm7a', 'sm7a']],
  ['sv6', 'Twilight Masquerade', ['sv6', 'twm']],
  ['sm5', 'Ultra Prism', ['sm5', 'upr']],
  ['sm10', 'Unbroken Bonds', ['sm10', 'unb']],
  ['sm11', 'Unified Minds', ['sm11', 'unm']],
  ['ex10', 'Unseen Forces', ['ex10', 'uf']],
  ['clf', 'Venusaur & Lugia ex Deck (JP)', ['clf', 'liga-clf']],
  ['swsh4', 'Vivid Voltage', ['swsh4', 'viv']],
  ['sk', 'VSTAR Premium Trainer Box', ['liga-sk', 'sk']],
  ['wpr', 'Wizards Black Star Promos', ['basep', 'wpr']],
  ['08c', 'World Championship 2008: Intimidation', ['08c', 'liga-08c']],
  ['08d', 'World Championship 2008: Psychic Lock', ['08d', 'liga-08d']],
  ['10b', 'World Championship 2010: Happy Luck', ['10b', 'liga-10b']],
  ['10d', 'World Championship 2010: Power Cottonweed', ['10d', 'liga-10d']],
  ['12c', 'World Championship 2012: Pesadelo Prism', ['12c', 'liga-12c']],
  ['13a', 'World Championship 2013: American Gothic', ['13a', 'liga-13a']],
  ['13c', 'World Championship 2013: Darkrai Deck', ['13c', 'liga-13c']],
  ['15a', 'World Championship 2015: Honorstoise', ['15a', 'liga-15a']],
  ['15b', 'World Championship 2015: Primal Groudon', ['15b', 'liga-15b']],
  ['15c', 'World Championship 2015: Punches \'N\' Bites', ['15c', 'liga-15c']],
  ['15d', 'World Championship 2015: The Flying Hammer', ['15d', 'liga-15d']],
  ['17b', 'World Championship 2017: Ice Path FTW', ['17b', 'liga-17b']],
  ['19a', 'World Championship 2019: Fire Box', ['19a', 'liga-19a']],
  ['19d', 'World Championship 2019: Pikarom Judge', ['19d', 'liga-19d']],
  ['23b', 'World Championship 2023: Colorless Lugia', ['23b', 'liga-23b']],
  ['23c', 'World Championship 2023: Lost Box Kyogre', ['23c', 'liga-23c']],
  ['23d', 'World Championship 2023: Psychic Elegance', ['23d', 'liga-23d']],
  ['xy1', 'XY', ['xy', 'xy1']],
]

const POR_SET = new Map<string, Familia>()
for (const [chave, nome, sets] of FAMILIAS) {
  const f = { chave, nome, sets }
  for (const s of sets) POR_SET.set(s, f)
}

/** Familia do set, ou null quando o set_id nao divide identidade com outro. */
export function familiaDoSet(setId?: string | null): Familia | null {
  return setId ? POR_SET.get(setId) || null : null
}
